---
title: "Knitting hats, scarves, and mittens"
author: "Alison Hill"
output:
  distill::distill_article:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE, fig.path="figs/")
```

## Data

http://langcog.github.io/wordbankr/

## Packages

```{r}
library(tidyverse)
library(wordbankr)
library(here)
library(paletteer)
ggplot2::theme_set(theme_minimal())
```

## Getting knitted things

```{r}
clothing <- get_item_data(
  language = "English (American)", 
  form = "WS"
  ) %>%
  filter(category == "clothing")

# selecting hat / scarf / mittens
knitted_things <- c("hat", "scarf", "mittens")

# get the items for my selected knitted things
my_knits <- get_item_data(
  language = "English (American)", 
  form = "WS"
  ) %>%
  filter(definition %in% knitted_things) 
```

```{r}
my_knits
```


## Get the instrument data for those knitted things

Focus on word production only.

```{r}
# then get instrument data for those items
word_items <- get_instrument_data(
  language = "English (American)",
  form = "WS",
  items = my_knits$item_id,
  administrations = TRUE,
  iteminfo = TRUE
  ) %>% 
  mutate(produces = value == "produces") %>% 
  select(-value) %>% 
  drop_na(produces) %>% 
  rename(word = uni_lemma) 
```

```{r}
word_items
```

## Check licenses

```{r}
word_items %>% 
  distinct(license)
```


## Summarize

What proportion of kids at each age produce each word?

```{r}
word_summary <- word_items %>% 
  group_by(age, word) %>%
  summarise(kids_produce = sum(produces, na.rm = TRUE),
            kids_n = n_distinct(data_id),
            prop_produce = kids_produce / kids_n) %>% 
  ungroup() %>% 
  # grab even ages only
  filter(age %% 2 == 0) %>% 
  select(age, word, prop_produce, kids_n)
```

```{r}
word_summary
```


## Explore ages

```{r ages}
ggplot(word_summary, aes(x = age, y = kids_n)) +
  geom_col(fill = "cadetblue", alpha = .5)
```



## Sample plot

```{r barplot}
words <-
  ggplot(word_summary, aes(x = age, y = prop_produce, color = word)) + 
  geom_smooth(se = FALSE, lwd = .5) +
  geom_point(size = 2)  +
  labs(x = "Age (months)", y = "Proportion of Children Producing") 
words
```

## Color palettes

```{r beyonce}
words + scale_color_paletteer_d("beyonce::X18")
```

```{r colorblind}
words + scale_color_paletteer_d("colorblindr::OkabeIto")
```

```{r saguaro}
words + scale_color_paletteer_d("nationalparkcolors::Saguaro")
```

```{r badlands}
words + scale_color_paletteer_d("nationalparkcolors::Badlands")
```

```{r picasso}
words + scale_color_paletteer_d("lisa::PabloPicasso")
```

```{r chagall}
words + scale_color_paletteer_d("lisa::MarcChagall")
```

```{r milkmaid}
words + scale_color_paletteer_d("dutchmasters::milkmaid")
```




## Crosslinguistic data

Could be great for parameters, or facetting?

```{r cache=TRUE}
knitted_langs <- get_crossling_data(uni_lemmas = knitted_things)
```

```{r cache=TRUE}
knitted_langs %>% 
  # grouped already? that is tricky
  ungroup() %>% 
  distinct(language)

# oof item ids are different
knitted_langs %>% 
  # grouped already? that is tricky
  ungroup() %>% 
  filter(uni_lemma == "scarf") %>% 
  distinct(item_id, language)
```

## Exporting

Now let's export both data frames.

```{r}
write_csv(word_items, 
          here::here("data","word_items.csv"))
write_csv(word_summary, 
          here::here("data","word_summary.csv"))
```

